# 开发环境的 compose 文件，merge into docker-compose.yml 文件
version: "3"
services:
  nginx:
    # 生产环境下对外映射 80 端口了，docker-compose.yml 中默认为 3000
    ports:
      - "80:80"

  node-app:
    build:
      context: .
      args:
        NODE_ENV: production
    environment:
      - NODE_ENV=production
      - MONGO_USER=yangyong
      - MONGO_PASSWORD=mypassword
      - SESSION_SECRET=mysecret
    command: node index.js